// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "title": "Qisur Challenge API",
        "description": "Backend API para gestión de productos y categorías con WebSockets",
        "version": "1.0.0"
    },
    "host": "localhost:8080",
    "basePath": "/api",
    "schemes": ["http"],
    "paths": {
        "/health": {
            "get": {
                "summary": "Health check",
                "tags": ["Health"],
                "responses": {
                    "200": {"description": "Server is healthy"}
                }
            }
        },
        "/auth/register": {
            "post": {
                "summary": "Register a new user",
                "tags": ["Auth"],
                "parameters": [{
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {
                        "type": "object",
                        "properties": {
                            "email": {"type": "string"},
                            "password": {"type": "string"}
                        }
                    }
                }],
                "responses": {
                    "201": {"description": "User created successfully"}
                }
            }
        },
        "/auth/login": {
            "post": {
                "summary": "Login user",
                "tags": ["Auth"],
                "parameters": [{
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {
                        "type": "object",
                        "properties": {
                            "email": {"type": "string"},
                            "password": {"type": "string"}
                        }
                    }
                }],
                "responses": {
                    "200": {"description": "Login successful"}
                }
            }
        },
        "/categories": {
            "get": {
                "summary": "List all categories",
                "tags": ["Categories"],
                "responses": {
                    "200": {"description": "List of categories"}
                }
            },
            "post": {
                "summary": "Create a new category (admin only)",
                "tags": ["Categories"],
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {
                        "type": "object",
                        "properties": {
                            "name": {"type": "string"},
                            "description": {"type": "string"}
                        }
                    }
                }],
                "responses": {
                    "201": {"description": "Category created"},
                    "401": {"description": "Unauthorized"},
                    "403": {"description": "Forbidden"}
                }
            }
        },
        "/categories/{id}": {
            "get": {
                "summary": "Get category by ID",
                "tags": ["Categories"],
                "parameters": [{
                    "name": "id",
                    "in": "path",
                    "required": true,
                    "type": "string"
                }],
                "responses": {
                    "200": {"description": "Category details"},
                    "404": {"description": "Category not found"}
                }
            },
            "put": {
                "summary": "Update category (admin only)",
                "tags": ["Categories"],
                "security": [{"BearerAuth": []}],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "name": {"type": "string"},
                                "description": {"type": "string"}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {"description": "Category updated"}
                }
            },
            "delete": {
                "summary": "Delete category (admin only)",
                "tags": ["Categories"],
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "name": "id",
                    "in": "path",
                    "required": true,
                    "type": "string"
                }],
                "responses": {
                    "204": {"description": "Category deleted"}
                }
            }
        },
        "/products": {
            "get": {
                "summary": "List all products",
                "tags": ["Products"],
                "parameters": [
                    {"name": "page", "in": "query", "type": "integer"},
                    {"name": "limit", "in": "query", "type": "integer"}
                ],
                "responses": {
                    "200": {"description": "List of products"}
                }
            },
            "post": {
                "summary": "Create a new product (admin only)",
                "tags": ["Products"],
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {
                        "type": "object",
                        "properties": {
                            "name": {"type": "string"},
                            "description": {"type": "string"},
                            "price": {"type": "number"},
                            "stock": {"type": "integer"},
                            "category_ids": {"type": "array"}
                        }
                    }
                }],
                "responses": {
                    "201": {"description": "Product created"},
                    "401": {"description": "Unauthorized"},
                    "403": {"description": "Forbidden"}
                }
            }
        },
        "/products/{id}": {
            "get": {
                "summary": "Get product by ID",
                "tags": ["Products"],
                "parameters": [{
                    "name": "id",
                    "in": "path",
                    "required": true,
                    "type": "string"
                }],
                "responses": {
                    "200": {"description": "Product details"},
                    "404": {"description": "Product not found"}
                }
            },
            "put": {
                "summary": "Update product (admin only)",
                "tags": ["Products"],
                "security": [{"BearerAuth": []}],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "name": {"type": "string"},
                                "description": {"type": "string"},
                                "price": {"type": "number"},
                                "stock": {"type": "integer"},
                                "category_ids": {"type": "array"}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {"description": "Product updated"}
                }
            },
            "delete": {
                "summary": "Delete product (admin only)",
                "tags": ["Products"],
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "name": "id",
                    "in": "path",
                    "required": true,
                    "type": "string"
                }],
                "responses": {
                    "204": {"description": "Product deleted"}
                }
            }
        },
        "/products/{id}/history": {
            "get": {
                "summary": "Get product history (price and stock changes)",
                "tags": ["Products"],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"},
                    {"name": "start", "in": "query", "type": "string", "description": "Start date (YYYY-MM-DD)"},
                    {"name": "end", "in": "query", "type": "string", "description": "End date (YYYY-MM-DD)"},
                    {"name": "limit", "in": "query", "type": "integer"},
                    {"name": "offset", "in": "query", "type": "integer"}
                ],
                "responses": {
                    "200": {"description": "Product history"}
                }
            }
        },
        "/search": {
            "get": {
                "summary": "Search products or categories",
                "tags": ["Search"],
                "parameters": [
                    {"name": "type", "in": "query", "required": true, "type": "string", "enum": ["product", "category"]},
                    {"name": "min_price", "in": "query", "type": "number"},
                    {"name": "max_price", "in": "query", "type": "number"},
                    {"name": "sort_by", "in": "query", "type": "string"},
                    {"name": "order", "in": "query", "type": "string", "enum": ["ASC", "DESC"]},
                    {"name": "page", "in": "query", "type": "integer"},
                    {"name": "limit", "in": "query", "type": "integer"}
                ],
                "responses": {
                    "200": {"description": "Search results"}
                }
            }
        },
        "/ws": {
            "get": {
                "summary": "WebSocket connection for real-time events",
                "tags": ["WebSocket"],
                "parameters": [{
                    "name": "token",
                    "in": "query",
                    "required": true,
                    "type": "string",
                    "description": "JWT token from /api/auth/login"
                }],
                "responses": {
                    "101": {"description": "Switching Protocols (WebSocket upgrade)"},
                    "401": {"description": "Unauthorized - invalid token"}
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

func init() {
	swag.Register(swag.Name, &swag.Spec{
		Version:     "1.0.0",
		Host:        "localhost:8080",
		BasePath:    "/api",
		Schemes:     []string{"http"},
		Title:       "Qisur Challenge API",
		Description: "Backend API para gestión de productos y categorías",
		InfoInstanceName: "swagger",
		SwaggerTemplate: docTemplate,
	})
}
